[package]
name        = "zydis"
version     = "0.0.4"
authors     = [
    "Joel Höner <joel@zyantific.com>",
    "Timo von Hartz <c0untlizzi@gmail.com>"
]

description = "Bindings for Zydis"
license     = "MIT"
keywords    = ["disassembler", "x86", "amd64", "decoder"]
repository  = "https://github.com/zyantific/zydis-rs/"

[build-dependencies]
cmake = "0.1"

[dependencies]
bitflags = "1.0"
serde = { version = "1.0", optional = true}
serde_derive = { version = "1.0", optional = true}

[features]
default = ["use_libc"]
serialization = ["serde", "serde_derive"]
use_libc = []

